name: healthcare_mania_legacy_new
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.5.0+6

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.3
  path_provider: ^2.0.11
  intl: ^0.17.0
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
